## Machine Learning - Session 1 - NumPy

In [1]:
#Import the numpy library
import numpy as np

#### A. Defining a 1D numpy array

In [2]:
x=np.array([12,34,76,875,56])
x

array([ 12,  34,  76, 875,  56])

#### B. Creating Regular Sequence

In [3]:
#Create a regular sequence of integers starting from 1 to 10. integers = c(1,2,3,4,.......,10)
integers=np.arange(10,0,-1)
integers


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [4]:
#Create a regular sequence of integers starting from 10 to 1.



In [5]:
#Create a regular sequence of even integers between 10 to 20
integers=np.arange(0,20,0.5)
integers


array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,
        13.5,  14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,
        18. ,  18.5,  19. ,  19.5])

In [6]:
#Create a regular sequence of the following type: [10.0,10.5,11.0,11.5, ... , 19.5, 20.0]



In [7]:
#Create a regular sequence of length 20 ranging from 0 to 5
np.linspace(start=0, stop=5, num=20, endpoint= True)
#np.linspace(start=0, stop=5, num=20, endpoint= False)
np.linspace(0, 5, 20, True, True)

(array([ 0.        ,  0.26315789,  0.52631579,  0.78947368,  1.05263158,
         1.31578947,  1.57894737,  1.84210526,  2.10526316,  2.36842105,
         2.63157895,  2.89473684,  3.15789474,  3.42105263,  3.68421053,
         3.94736842,  4.21052632,  4.47368421,  4.73684211,  5.        ]),
 0.26315789473684209)

In [8]:
#Help for np.linspace

help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [9]:
#Studying the arange function

help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

#### C. Creating a Random Sequence

In [10]:
#Generate 20 random numbers between 1 and 100
np.random.seed(10) #seed will help you get same random numbers on different machines
np.random.randint(50,100,20)

array([59, 86, 65, 50, 99, 78, 75, 79, 98, 79, 99, 58, 59, 50, 92, 90, 86,
       66, 86, 97])

In [11]:
#Shuffle the vector x
x= np.array([12,23,35,12,60])
np.random.shuffle(x)
x

array([60, 23, 12, 35, 12])

In [12]:
#Permute x and return it
x= np.array([12,23,35,12,60])
np.random.permutation(x)

array([12, 12, 23, 60, 35])

In [13]:
x= np.array([12,23,35,12,60])
np.random.choice(x,3)

array([60, 23, 12])

In [14]:
#help(np.random.choice)

To find more on numpy random sampling Go To this link 
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html 

#### D. Some basic numpy methods

In [15]:
x = np.array([12,34,24.0,45,7,18])

In [16]:
x

array([ 12.,  34.,  24.,  45.,   7.,  18.])

In [17]:
#Size of the array
x.size

6

In [18]:
#Type of the object
x.dtype

dtype('float64')

In [19]:
type(x)

numpy.ndarray

In [20]:
#Type conversion
x.astype(str)

array(['12.0', '34.0', '24.0', '45.0', '7.0', '18.0'],
      dtype='<U32')

In [21]:
x.astype(int)

array([12, 34, 24, 45,  7, 18])

#### E. Some basic (1D) numpy operations

In [22]:
#Consider that we have two arrays

x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [23]:
#Addition
x + y

array([15, 40, 32, 50,  8, 28])

In [24]:
#Subtraction
y - x

array([ -9, -28, -16, -40,  -6,  -8])

In [25]:
#Multiplication by scalar
y*10

array([ 30,  60,  80,  50,  10, 100])

In [26]:
#Element wise multiplication (dot product)
x*y

array([ 36, 204, 192, 225,   7, 180])

In [27]:
#Using dot method
x.dot(y)

844

In [28]:
y.dot(x)

844

In [29]:
np.dot(x,y)

844

In [30]:
#Squaring each elements in an array
x**2

array([ 144, 1156,  576, 2025,   49,  324])

#### F. Some Useful Numpy Functions

In [31]:
y = np.array([3,6,8,5,1,10])

In [32]:
#Sum
np.sum(y)

33

In [33]:
#Mean
np.mean(x)

23.333333333333332

In [34]:
#Standard Deviation
np.std(y)

2.9860788111948193

In [35]:
#Minimum
np.min(y)

1

In [36]:
#Maximum
np.max(y)

10

In [37]:
#Percentiles
np.percentile(y,0.25)

1.0250000000000001

In [38]:
np.percentile(y,[0.25,0.75])

array([ 1.025,  1.075])

In [39]:
#Sorting
np.sort(y)

array([ 1,  3,  5,  6,  8, 10])

#### G. Subsetting a 1D numpy array

In [40]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [41]:
#Subsetting and slicing is same as list
x[1:]

array([34, 24, 45,  7, 18])

In [42]:
y[1:5]

array([6, 8, 5, 1])

#### H. Conditional Subsetting

**The Comparison Operators**

      > is greater than
      < is less than
      == is equal to
      <= is less than equal to
      >= is greater than equal to

In [59]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [60]:
x>20 

array([False,  True,  True,  True, False, False], dtype=bool)

In [61]:
y==1

array([False, False, False, False,  True, False], dtype=bool)

**The Logical Operators**

    AND: &
    OR : |

In [62]:
(y>20) | (y==5)

array([False, False, False,  True, False, False], dtype=bool)

In [47]:
(x>20) & (y<10)

array([False,  True,  True,  True, False, False], dtype=bool)

**Problems**

In [48]:
#Consider the following two vectors

x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

In [49]:
#a. Vaues of x that are less than 35
x[x<35]


array([33, 23])

In [50]:
#b. The number of observations in y that are more than 150
len(y[y>150])
y[y>150].size

2

In [51]:
#OR
sum(y>50)

6

In [52]:
#c. The number of observations in y that are between 120 and 165
len(y[(y>120) & (y<165)])


4

In [53]:
#d. The vaues in x that are less than 30 or greater than 50
x[(x<30) | (x>50)]

array([23, 67, 54])

In [54]:
#e. The values in x for which the values in y is less than or equal to 120
x[y<=120]

array([33, 67])

In [55]:
#f. The values in y for which the values in x is equal to 45
y[x==45]

array([151])

#### I. Defining a 2D numpy array

In [66]:
#Converting a 1D array into 2D array
x = np.array([33,45,23,67,54,48])
matrix= x.reshape(2,3)
matrix

array([[33, 45, 23],
       [67, 54, 48]])

In [57]:
matrix= x.reshape(3,3)
marix

ValueError: cannot reshape array of size 6 into shape (3,3)

In [67]:
x= np.arange(1,10,1)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
#Create a 3x3 matrix containing elements from 1 to 9
x.reshape(3,3) #or np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
#Joining two 1D arrays to form a matrix
x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])
m= np.array([x,y])
m

array([[ 33,  45,  23,  67,  54,  48],
       [108, 151, 164, 119, 135, 122]])

#### J. Some basic methods for 2D numpy array

In [70]:
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [71]:
#Checking the shape of the matrix
matrix.shape

(5, 3)

In [72]:
#Dimension of the array
matrix.ndim

2

In [73]:
#Data type of the elements in the array
matrix.dtype

dtype('int64')

In [74]:
matrix.size

15

In [75]:
#Number of elements present in the matrix


In [76]:
#Size of the matrix in bytes
matrix.itemsize

8

#### K. Subsetting 2D numpy array

In [77]:
#matrix
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])


In [78]:
#a) Print the first element of the matrix.
matrix[0,0]


38

In [79]:
#b) Print the last element of the matrix.
matrix[matrix.shape[0]-1,matrix.shape[1]-1]

43

In [80]:
#Or
matrix[-1,-1]

43

In [81]:
#c) Print the values of the first row.
matrix[0,0:]

array([38, 33, 47])

In [82]:
#d) Print the values of the fourth row.
matrix[3,0:]

array([38, 44, 21])

In [83]:
#e) Print the values first column.
matrix[0:,0]

array([38, 29, 21, 38, 28])

In [84]:
#f) Calculate the total of the third row.
sum(matrix[2,0:])

102

In [85]:
#g) Calculate the total of the fifth row.
sum(matrix[4,0:])

97

In [86]:
#h) Calculate the total of the second column.
sum(matrix[0:,1])

185

In [87]:
#i) Calculate the average of the values of the first row.
np.average(matrix[0,0:])

39.333333333333336

In [88]:
#j) Replace the first value of the matrix by 50.
matrix[0,0]=50



In [89]:
#k) Replace the last value of the matrix by 30.
matrix[-1,-1]=30


In [90]:
#l) Replace the second column of the matrix by the vector (20,30,20,30,20)
matrix[0:,1]=(20,30,20,30,20)



In [91]:
#m) Replace the first row of the matrix by the vector its average (calculated above).
#matrix(0,0)=np.average(matrix[0,0:])
matrix[0,0]=np.mean(matrix[0,0:])

In [92]:
matrix

array([[39, 20, 47],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 30]])

In [93]:
#q) Calculate the sum of all the elements of the matrix
sum(sum(matrix[0:,0:]))

455

In [94]:
help(np.sum)

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  I

In [95]:
#r) Calculate the sum of all the rows on the matrix
np.sum(matrix, axis=0)

array([155, 120, 180])

In [96]:
#s) Calculate the sum of all the colummns of the matrix
np.sum(matrix, axis=1)

array([106,  94,  88,  89,  78])

#### L. Matrix Operations

In [97]:
#Defining a matrix 'm'
m = np.array([[2,3],[4,5]])
m

array([[2, 3],
       [4, 5]])

In [98]:
#Defining a matrix 'n'
n = np.array([[1,0],[3,6]])
n

array([[1, 0],
       [3, 6]])

In [99]:
#Multiplication by scalar
2*m

array([[ 4,  6],
       [ 8, 10]])

In [100]:
#Matrix addition
m+n

array([[ 3,  3],
       [ 7, 11]])

In [101]:
#Matrix Multilication
np.dot(m,n)

array([[11, 18],
       [19, 30]])

In [102]:
#Preferred - for Matrix Multilication
np.matmul(m,n)

array([[11, 18],
       [19, 30]])

In [103]:
#Preferred - for Matrix Multilication
m @ n 

array([[11, 18],
       [19, 30]])

In [104]:
#Element-wise array multilication
np.multiply(n,m)

array([[ 2,  0],
       [12, 30]])

#### Copying data

In [105]:
p = np.array([2,5,8,6])

In [106]:
q=p

In [107]:
q[2]=10

In [108]:
q

array([ 2,  5, 10,  6])

In [109]:
p

array([ 2,  5, 10,  6])

In [110]:
q= p.copy()

In [111]:
q[2]= 100

In [112]:
q

array([  2,   5, 100,   6])

In [113]:
p

array([ 2,  5, 10,  6])